import { PlanetData, PlanetArchetype, MineralDeposit } from '../types';

export const STANDARD_MINERALS: MineralDeposit[] = [
  {
    id: 'min_ree',
    name: 'Rare Earth Elements (Nd, Dy, Eu)',
    symbol: 'REE',
    category: 'rare_earth',
    crustalAbundancePpm: 185,
    economicValueTier: 'strategic',
    geologicalOrigin: 'Hydrothermal carbonatite veins and alkaline igneous intrusions',
    heatmapColor: '#a855f7', // Violet
  },
  {
    id: 'min_pgm',
    name: 'Platinum Group Metals (Pt, Ir, Os)',
    symbol: 'PGM',
    category: 'platinum_group',
    crustalAbundancePpm: 0.045,
    economicValueTier: 'ultra_rare',
    geologicalOrigin: 'Layered ultramafic intrusions and bolide impact melts',
    heatmapColor: '#06b6d4', // Cyan
  },
  {
    id: 'min_iron_ti',
    name: 'Titanomagnetite & BIF Iron',
    symbol: 'Fe-Ti',
    category: 'structural',
    crustalAbundancePpm: 58000,
    economicValueTier: 'essential',
    geologicalOrigin: 'Banded iron formations and anorthositic complexes',
    heatmapColor: '#f97316', // Orange
  },
  {
    id: 'min_fissile',
    name: 'Actinides (Uranium & Thorium)',
    symbol: 'U/Th',
    category: 'energy_fissile',
    crustalAbundancePpm: 8.5,
    economicValueTier: 'strategic',
    geologicalOrigin: 'Fractionated granitic pegmatites and roll-front sandstones',
    heatmapColor: '#22c55e', // Emerald Green
  },
  {
    id: 'min_volatiles',
    name: 'Clathrate Hydrates & Methane Ice',
    symbol: 'CH4-H2O',
    category: 'volatile',
    crustalAbundancePpm: 1200,
    economicValueTier: 'high',
    geologicalOrigin: 'Subsea continental margins and cryospheric permafrost',
    heatmapColor: '#38bdf8', // Ice Blue
  },
  {
    id: 'min_superconductor',
    name: 'Metamorphic Chalcogenides',
    symbol: 'χ-Chalc',
    category: 'exotic',
    crustalAbundancePpm: 0.003,
    economicValueTier: 'ultra_rare',
    geologicalOrigin: 'Ultra-high pressure mantle shear zones and core-mantle boundary diapirs',
    heatmapColor: '#e11d48', // Crimson Red
  },
];

export const PRESET_PLANETS: Record<PlanetArchetype, PlanetData> = {
  earth_like: {
    id: 'planet-earth-gaia',
    name: 'Nova Terra (Gaia Prime)',
    seed: 1492,
    archetype: 'earth_like',
    description: 'A thriving terrestrial garden world orbiting a sun-like G2V star with an oxygen-nitrogen atmosphere, dynamic oceans, and active plate tectonics.',
    radiusEarth: 1.02,
    massEarth: 1.05,
    densityGcm3: 5.48,
    surfaceGravityG: 1.01,
    escapeVelocityKms: 11.35,
    magneticFieldGauss: 0.52,
    semiMajorAxisAU: 1.03,
    eccentricity: 0.021,
    orbitalInclinationDeg: 1.8,
    argumentOfPeriapsisDeg: 114,
    orbitalPeriodDays: 378.4,
    axialTiltDeg: 22.8,
    rotationPeriodHours: 24.6,
    star: {
      name: 'Helios Prime',
      spectralType: 'G',
      massSolar: 1.02,
      luminositySolar: 1.05,
      radiusSolar: 1.01,
      effectiveTemperatureK: 5820,
      starColorHex: '#fff7ed',
      habitableZoneInnerAU: 0.97,
      habitableZoneOuterAU: 1.72,
    },
    moons: [
      {
        id: 'moon-luna-prime',
        name: 'Selene Alpha',
        radiusEarth: 0.28,
        massEarth: 0.013,
        semiMajorAxisKm: 395000,
        eccentricity: 0.045,
        inclinationDeg: 4.8,
        orbitalPeriodDays: 28.5,
        isTidallyLocked: true,
        albedo: 0.14,
        colorHex: '#e2e8f0',
        hasAtmosphere: false,
      },
    ],
    atmosphere: {
      surfacePressureAtm: 1.03,
      scaleHeightKm: 8.4,
      gases: [
        { name: 'Nitrogen', symbol: 'N2', percentage: 76.8, greenhouseEffect: 0.0 },
        { name: 'Oxygen', symbol: 'O2', percentage: 21.4, greenhouseEffect: 0.0 },
        { name: 'Argon', symbol: 'Ar', percentage: 0.93, greenhouseEffect: 0.0 },
        { name: 'Water Vapor', symbol: 'H2O', percentage: 0.82, greenhouseEffect: 0.65 },
        { name: 'Carbon Dioxide', symbol: 'CO2', percentage: 0.05, greenhouseEffect: 0.35 },
      ],
      greenhouseFactorK: 34,
      skyColorHex: '#38bdf8',
      sunsetGlowHex: '#f97316',
      cloudCoveragePercent: 54,
      hazeDensity: 0.12,
      breathableHuman: true,
      toxicityAlerts: [],
    },
    seaLevelPercent: 68,
    albedo: 0.31,
    meanAnnualSurfaceTempC: 15.4,
    seasonalTempVarianceC: 14.5,
    meanAnnualPrecipitationMm: 1040,
    plateCount: 9,
    plates: [
      { id: 1, name: 'Oceanic Abyssal Plate', isOceanic: true, centerLat: -15, centerLon: -110, velocityMmYr: 65, headingDeg: 285, color: '#3b82f6' },
      { id: 2, name: 'Laurentian Shield Plate', isOceanic: false, centerLat: 35, centerLon: -60, velocityMmYr: 25, headingDeg: 310, color: '#10b981' },
      { id: 3, name: 'Eurasian Core Plate', isOceanic: false, centerLat: 42, centerLon: 40, velocityMmYr: 20, headingDeg: 80, color: '#f59e0b' },
      { id: 4, name: 'Southern Gondwana Plate', isOceanic: false, centerLat: -30, centerLon: 25, velocityMmYr: 32, headingDeg: 15, color: '#8b5cf6' },
      { id: 5, name: 'Pacific Rim Ocean Plate', isOceanic: true, centerLat: 10, centerLon: 140, velocityMmYr: 75, headingDeg: 295, color: '#06b6d4' },
      { id: 6, name: 'Australis Basin Plate', isOceanic: false, centerLat: -45, centerLon: 115, velocityMmYr: 45, headingDeg: 40, color: '#ec4899' },
    ],
    deepTimeMa: 0,
    minerals: STANDARD_MINERALS,
    isHabitable: true,
    calendar: {
      yearName: 'Gaian Solar Cycle',
      hoursPerDay: 24.6,
      daysPerYear: 369,
      months: [
        { name: 'Primus', days: 31 }, { name: 'Verdant', days: 31 }, { name: 'Floralia', days: 31 },
        { name: 'Solstice', days: 31 }, { name: 'Aestival', days: 31 }, { name: 'Maturis', days: 31 },
        { name: 'Autumnal', days: 30 }, { name: 'Equinox', days: 31 }, { name: 'Borealis', days: 31 },
        { name: 'Frostfall', days: 31 }, { name: 'Bruma', days: 31 }, { name: 'Novalis', days: 30 },
      ],
      weekdays: ['Soladay', 'Terraday', 'Lunaday', 'Martiday', 'Aetherday', 'Stelladay', 'Otioday'],
      currentYear: 342,
      currentMonth: 4,
      currentDay: 18,
      currentHour: 14,
    },
    eras: [
      { id: 'era-1', name: 'Dawn of Oceanic Life', startYear: -2000000000, endYear: -600000000, description: 'Single-celled cyanobacterial mats develop first oxygenated oceans.' },
      { id: 'era-2', name: 'First Terrestrial Settlements', startYear: 1, endYear: 120, description: 'Interstellar colonist generation ships land in the Great Coastal Valley.' },
      { id: 'era-3', name: 'Industrial & Maglev Zenith', startYear: 121, endYear: 280, description: 'Subsurface vacuum train corridors span the continents.' },
      { id: 'era-4', name: 'Interplanetary Expansion', startYear: 281, endYear: 350, description: 'Orbital elevator construction and lunar mining station expansion.' },
    ],
    chronicle: [
      { id: 'ev-1', year: 12, planetDay: 84, eraId: 'era-2', title: 'The Great Touchdown', category: 'sociopolitical', description: 'Ark Ship Prometheus anchors in orbit and begins automated habitat deployments.' },
      { id: 'ev-2', year: 88, planetDay: 142, eraId: 'era-2', title: 'Great Total Solar Eclipse', category: 'astronomical', isEclipse: true, eclipseType: 'solar_total', description: 'Selene Alpha occults Helios Prime for 4.2 minutes of total darkness over the capital basin.' },
      { id: 'ev-3', year: 195, planetDay: 210, eraId: 'era-3', title: 'Trans-Oceanic Maglev Inauguration', category: 'technological', description: 'Submarine vacuum tunnel connects Laurentia and Eurasia.' },
      { id: 'ev-4', year: 310, planetDay: 44, eraId: 'era-4', title: 'Orbital Ring Completion', category: 'technological', description: 'Geostationary space tether tethered to equatorial anchor station.' },
    ],
    lastModified: Date.now(),
  },

  mars_like: {
    id: 'planet-mars-ares',
    name: 'Ares Secundus',
    seed: 3844,
    archetype: 'mars_like',
    description: 'A cold, hyper-arid rust world with massive shield volcanoes, profound canyon rift systems, and thin carbon dioxide skies.',
    radiusEarth: 0.54,
    massEarth: 0.11,
    densityGcm3: 3.94,
    surfaceGravityG: 0.38,
    escapeVelocityKms: 5.04,
    magneticFieldGauss: 0.02,
    semiMajorAxisAU: 1.52,
    eccentricity: 0.093,
    orbitalInclinationDeg: 2.1,
    argumentOfPeriapsisDeg: 286,
    orbitalPeriodDays: 686.9,
    axialTiltDeg: 25.2,
    rotationPeriodHours: 24.62,
    star: {
      name: 'Helios Prime',
      spectralType: 'G',
      massSolar: 1.0,
      luminositySolar: 1.0,
      radiusSolar: 1.0,
      effectiveTemperatureK: 5778,
      starColorHex: '#fff7ed',
      habitableZoneInnerAU: 0.95,
      habitableZoneOuterAU: 1.68,
    },
    moons: [
      {
        id: 'moon-phobos-analog',
        name: 'Deimos Minor',
        radiusEarth: 0.003,
        massEarth: 0.0000001,
        semiMajorAxisKm: 14200,
        eccentricity: 0.015,
        inclinationDeg: 1.1,
        orbitalPeriodDays: 0.72,
        isTidallyLocked: true,
        albedo: 0.07,
        colorHex: '#94a3b8',
        hasAtmosphere: false,
      },
    ],
    atmosphere: {
      surfacePressureAtm: 0.012,
      scaleHeightKm: 11.2,
      gases: [
        { name: 'Carbon Dioxide', symbol: 'CO2', percentage: 95.3, greenhouseEffect: 0.8 },
        { name: 'Nitrogen', symbol: 'N2', percentage: 2.7, greenhouseEffect: 0.0 },
        { name: 'Argon', symbol: 'Ar', percentage: 1.6, greenhouseEffect: 0.0 },
        { name: 'Water Vapor', symbol: 'H2O', percentage: 0.03, greenhouseEffect: 0.2 },
      ],
      greenhouseFactorK: 6,
      skyColorHex: '#fb923c', // Butterscotch dust sky
      sunsetGlowHex: '#38bdf8', // Blue Martian sunset
      cloudCoveragePercent: 8,
      hazeDensity: 0.45,
      breathableHuman: false,
      toxicityAlerts: ['Near vacuum pressure (Armstrong limit exceeded)', 'Extreme hypercapnia (95% CO2)', 'Unfiltered UV-C radiation flux'],
    },
    seaLevelPercent: 0,
    albedo: 0.25,
    meanAnnualSurfaceTempC: -62.5,
    seasonalTempVarianceC: 38.0,
    meanAnnualPrecipitationMm: 18,
    plateCount: 4,
    plates: [
      { id: 1, name: 'Tharsis Volcanic Plateau Plate', isOceanic: false, centerLat: 10, centerLon: -100, velocityMmYr: 4, headingDeg: 90, color: '#f97316' },
      { id: 2, name: 'Valles Marineris Rift Basin', isOceanic: false, centerLat: -14, centerLon: -60, velocityMmYr: 3, headingDeg: 180, color: '#ef4444' },
      { id: 3, name: 'Hellas Impact Lowlands', isOceanic: false, centerLat: -42, centerLon: 70, velocityMmYr: 2, headingDeg: 0, color: '#8b5cf6' },
      { id: 4, name: 'Northern Vastitas Wasteland', isOceanic: false, centerLat: 60, centerLon: 10, velocityMmYr: 1, headingDeg: 270, color: '#a855f7' },
    ],
    deepTimeMa: 0,
    minerals: STANDARD_MINERALS,
    isHabitable: false,
    calendar: {
      yearName: 'Arean Sol Year',
      hoursPerDay: 24.62,
      daysPerYear: 668,
      months: [
        { name: 'Sagitta', days: 56 }, { name: 'Dorado', days: 56 }, { name: 'Aquila', days: 56 },
        { name: 'Vulpecula', days: 56 }, { name: 'Cygnus', days: 55 }, { name: 'Pegasus', days: 56 },
        { name: 'Equuleus', days: 55 }, { name: 'Lacerta', days: 56 }, { name: 'Andromeda', days: 56 },
        { name: 'Cassiopeia', days: 56 }, { name: 'Perseus', days: 55 }, { name: 'Triangulum', days: 55 },
      ],
      weekdays: ['Sol-1', 'Sol-2', 'Sol-3', 'Sol-4', 'Sol-5', 'Sol-6', 'Sol-7'],
      currentYear: 45,
      currentMonth: 2,
      currentDay: 24,
      currentHour: 8,
    },
    eras: [
      { id: 'era-m1', name: 'Noachian Wet Epoch', startYear: -3800000000, endYear: -3500000000, description: 'Primordial rivers carved ancient dendritic valleys before dynamo shutdown.' },
      { id: 'era-m2', name: 'Amazonian Desolation', startYear: -3000000000, endYear: -100000, description: 'Atmosphere stripped by solar wind; planet freezes into red wasteland.' },
      { id: 'era-m3', name: 'Dome Colony Era', startYear: 1, endYear: 150, description: 'Pressurized subterranean lava tube cities established by mineral cartels.' },
    ],
    chronicle: [
      { id: 'ev-m1', year: 8, planetDay: 112, eraId: 'era-m3', title: 'Olympus Mons Deep Core Discovery', category: 'technological', description: 'Geothermal geothermal tap strikes liquid water reservoir at 12km depth.' },
      { id: 'ev-m2', year: 42, planetDay: 380, eraId: 'era-m3', title: 'Great Dust Storm of Sol 380', category: 'ecological', description: 'Global encircling storm shrouds solar arrays for 110 sols.' },
    ],
    lastModified: Date.now(),
  },

  super_earth: {
    id: 'planet-super-earth-titan',
    name: 'Aethelgard (Super-Earth)',
    seed: 9182,
    archetype: 'super_earth',
    description: 'A colossal rocky super-earth with 1.62 Earth radii and 3.8 Earth masses. Features punishing 1.45g gravity, thick 2.3 atm atmosphere, and immense orogenic folding.',
    radiusEarth: 1.62,
    massEarth: 3.8,
    densityGcm3: 5.92,
    surfaceGravityG: 1.45,
    escapeVelocityKms: 17.15,
    magneticFieldGauss: 1.85, // Super-strong dynamo
    semiMajorAxisAU: 1.15,
    eccentricity: 0.038,
    orbitalInclinationDeg: 3.4,
    argumentOfPeriapsisDeg: 45,
    orbitalPeriodDays: 452.1,
    axialTiltDeg: 19.5,
    rotationPeriodHours: 18.2, // Rapid rotation
    star: {
      name: 'Kepler-442 Analog',
      spectralType: 'K',
      massSolar: 0.92,
      luminositySolar: 0.72,
      radiusSolar: 0.88,
      effectiveTemperatureK: 5200,
      starColorHex: '#fde047',
      habitableZoneInnerAU: 0.81,
      habitableZoneOuterAU: 1.42,
    },
    moons: [
      {
        id: 'moon-titan-1',
        name: 'Valkyrie',
        radiusEarth: 0.42,
        massEarth: 0.045,
        semiMajorAxisKm: 520000,
        eccentricity: 0.02,
        inclinationDeg: 8.5,
        orbitalPeriodDays: 21.4,
        isTidallyLocked: true,
        albedo: 0.22,
        colorHex: '#cbd5e1',
        hasAtmosphere: true,
      },
    ],
    atmosphere: {
      surfacePressureAtm: 2.35,
      scaleHeightKm: 6.2, // Dense scale height
      gases: [
        { name: 'Nitrogen', symbol: 'N2', percentage: 81.0, greenhouseEffect: 0.0 },
        { name: 'Oxygen', symbol: 'O2', percentage: 17.5, greenhouseEffect: 0.0 },
        { name: 'Argon', symbol: 'Ar', percentage: 1.2, greenhouseEffect: 0.0 },
        { name: 'Water Vapor', symbol: 'H2O', percentage: 0.25, greenhouseEffect: 0.7 },
        { name: 'Carbon Dioxide', symbol: 'CO2', percentage: 0.05, greenhouseEffect: 0.3 },
      ],
      greenhouseFactorK: 48,
      skyColorHex: '#0284c7', // Deep indigo-azure
      sunsetGlowHex: '#e11d48',
      cloudCoveragePercent: 68,
      hazeDensity: 0.2,
      breathableHuman: true,
      toxicityAlerts: ['High barometric pressure (nitrogen narcosis risk at deep elevations)'],
    },
    seaLevelPercent: 74,
    albedo: 0.35,
    meanAnnualSurfaceTempC: 18.8,
    seasonalTempVarianceC: 9.2,
    meanAnnualPrecipitationMm: 1480,
    plateCount: 14,
    plates: [
      { id: 1, name: 'Great Boreal Mega-Craton', isOceanic: false, centerLat: 45, centerLon: -30, velocityMmYr: 42, headingDeg: 120, color: '#10b981' },
      { id: 2, name: 'Girdle Oceanic Basin', isOceanic: true, centerLat: 0, centerLon: 60, velocityMmYr: 95, headingDeg: 260, color: '#3b82f6' },
      { id: 3, name: 'Austral Shield Cordillera', isOceanic: false, centerLat: -40, centerLon: -90, velocityMmYr: 35, headingDeg: 340, color: '#f59e0b' },
      { id: 4, name: 'Mantle Plume Fracture Arc', isOceanic: true, centerLat: -10, centerLon: 160, velocityMmYr: 88, headingDeg: 45, color: '#06b6d4' },
    ],
    deepTimeMa: 0,
    minerals: STANDARD_MINERALS,
    isHabitable: true,
    calendar: {
      yearName: 'Aethel Solar Cycle',
      hoursPerDay: 18.2,
      daysPerYear: 596,
      months: [
        { name: 'Aethel-1', days: 50 }, { name: 'Aethel-2', days: 50 }, { name: 'Aethel-3', days: 50 },
        { name: 'Aethel-4', days: 50 }, { name: 'Aethel-5', days: 50 }, { name: 'Aethel-6', days: 50 },
        { name: 'Aethel-7', days: 49 }, { name: 'Aethel-8', days: 50 }, { name: 'Aethel-9', days: 49 },
        { name: 'Aethel-10', days: 49 }, { name: 'Aethel-11', days: 49 }, { name: 'Aethel-12', days: 50 },
      ],
      weekdays: ['Day-1', 'Day-2', 'Day-3', 'Day-4', 'Day-5', 'Day-6'],
      currentYear: 184,
      currentMonth: 6,
      currentDay: 12,
      currentHour: 9,
    },
    eras: [
      { id: 'era-s1', name: 'Mega-Fauna Evolutionary Epoch', startYear: -1000000, endYear: 0, description: 'Dense atmosphere allows gigantic airborne organisms to float effortlessly.' },
      { id: 'era-s2', name: 'High-Gravity Architecture Era', startYear: 1, endYear: 200, description: 'Constructing pyramid-reinforced low-profile subterranean colonies.' },
    ],
    chronicle: [
      { id: 'ev-s1', year: 34, planetDay: 190, eraId: 'era-s2', title: 'First Subsurface Maglev Spine', category: 'technological', description: 'Trans-continental subterranean rail network activated under 1.45g conditions.' },
      { id: 'ev-s2', year: 112, planetDay: 420, eraId: 'era-s2', title: 'Valkyrie Solar Occultation', category: 'astronomical', isEclipse: true, eclipseType: 'solar_total', description: 'Valkyrie eclipses the orange dwarf star for 9 minutes.' },
    ],
    lastModified: Date.now(),
  },

  oceanic: {
    id: 'planet-ocean-thalassa',
    name: 'Thalassa Pelagia',
    seed: 5521,
    archetype: 'oceanic',
    description: 'A global ocean world with 94% marine coverage, 80km deep abyssal trenches, floating sea-city networks, and extreme equatorial squall belts.',
    radiusEarth: 1.15,
    massEarth: 1.25,
    densityGcm3: 4.85,
    surfaceGravityG: 0.95,
    escapeVelocityKms: 11.6,
    magneticFieldGauss: 0.65,
    semiMajorAxisAU: 0.92,
    eccentricity: 0.012,
    orbitalInclinationDeg: 0.8,
    argumentOfPeriapsisDeg: 12,
    orbitalPeriodDays: 322.5,
    axialTiltDeg: 14.2,
    rotationPeriodHours: 26.1,
    star: {
      name: 'Sulis Star',
      spectralType: 'F',
      massSolar: 1.18,
      luminositySolar: 1.42,
      radiusSolar: 1.14,
      effectiveTemperatureK: 6350,
      starColorHex: '#fef08a',
      habitableZoneInnerAU: 1.13,
      habitableZoneOuterAU: 2.00,
    },
    moons: [],
    atmosphere: {
      surfacePressureAtm: 1.42,
      scaleHeightKm: 9.1,
      gases: [
        { name: 'Nitrogen', symbol: 'N2', percentage: 74.0, greenhouseEffect: 0.0 },
        { name: 'Oxygen', symbol: 'O2', percentage: 22.0, greenhouseEffect: 0.0 },
        { name: 'Water Vapor', symbol: 'H2O', percentage: 3.2, greenhouseEffect: 0.9 },
        { name: 'Carbon Dioxide', symbol: 'CO2', percentage: 0.04, greenhouseEffect: 0.3 },
      ],
      greenhouseFactorK: 42,
      skyColorHex: '#0ea5e9',
      sunsetGlowHex: '#f43f5e',
      cloudCoveragePercent: 78,
      hazeDensity: 0.18,
      breathableHuman: true,
      toxicityAlerts: [],
    },
    seaLevelPercent: 94,
    albedo: 0.34,
    meanAnnualSurfaceTempC: 22.5,
    seasonalTempVarianceC: 5.5,
    meanAnnualPrecipitationMm: 2450,
    plateCount: 7,
    plates: [
      { id: 1, name: 'Great Pelagic Plate', isOceanic: true, centerLat: 0, centerLon: 0, velocityMmYr: 70, headingDeg: 90, color: '#3b82f6' },
      { id: 2, name: 'Archipelago Ridge Arc', isOceanic: true, centerLat: 30, centerLon: 80, velocityMmYr: 85, headingDeg: 210, color: '#06b6d4' },
    ],
    deepTimeMa: 0,
    minerals: STANDARD_MINERALS,
    isHabitable: true,
    calendar: {
      yearName: 'Thalassian Tide Cycle',
      hoursPerDay: 26.1,
      daysPerYear: 296,
      months: [
        { name: 'Tide-1', days: 37 }, { name: 'Tide-2', days: 37 }, { name: 'Tide-3', days: 37 },
        { name: 'Tide-4', days: 37 }, { name: 'Tide-5', days: 37 }, { name: 'Tide-6', days: 37 },
        { name: 'Tide-7', days: 37 }, { name: 'Tide-8', days: 37 },
      ],
      weekdays: ['Ebb', 'Flow', 'Spring', 'Neap', 'Crest', 'Surge'],
      currentYear: 78,
      currentMonth: 3,
      currentDay: 19,
      currentHour: 15,
    },
    eras: [
      { id: 'era-o1', name: 'Floating Biosphere Integration', startYear: 1, endYear: 90, description: 'Construction of anchored floating geodesic seasteads.' },
    ],
    chronicle: [
      { id: 'ev-o1', year: 15, planetDay: 104, eraId: 'era-o1', title: 'Abyssal Thermal Vent Tap', category: 'technological', description: 'Geothermal turbines deployed at 9,000m hydrothermal vent chimneys.' },
    ],
    lastModified: Date.now(),
  },

  desert: {
    id: 'planet-desert-arrakis',
    name: 'Khorasan Secundus',
    seed: 7719,
    archetype: 'desert',
    description: 'A scorching dune world with deep canyon networks, mineral salt flats, and vast oceans of shifting sand with only polar water reservoirs.',
    radiusEarth: 0.94,
    massEarth: 0.82,
    densityGcm3: 5.42,
    surfaceGravityG: 0.93,
    escapeVelocityKms: 10.45,
    magneticFieldGauss: 0.38,
    semiMajorAxisAU: 0.88,
    eccentricity: 0.045,
    orbitalInclinationDeg: 4.1,
    argumentOfPeriapsisDeg: 88,
    orbitalPeriodDays: 298.5,
    axialTiltDeg: 28.5,
    rotationPeriodHours: 25.4,
    star: {
      name: 'Al-Shams',
      spectralType: 'F',
      massSolar: 1.15,
      luminositySolar: 1.35,
      radiusSolar: 1.12,
      effectiveTemperatureK: 6200,
      starColorHex: '#fef9c3',
      habitableZoneInnerAU: 1.10,
      habitableZoneOuterAU: 1.95,
    },
    moons: [
      {
        id: 'moon-dune-1',
        name: 'Qamar',
        radiusEarth: 0.18,
        massEarth: 0.005,
        semiMajorAxisKm: 260000,
        eccentricity: 0.02,
        inclinationDeg: 2.1,
        orbitalPeriodDays: 14.8,
        isTidallyLocked: true,
        albedo: 0.28,
        colorHex: '#e2e8f0',
        hasAtmosphere: false,
      },
    ],
    atmosphere: {
      surfacePressureAtm: 0.88,
      scaleHeightKm: 8.9,
      gases: [
        { name: 'Nitrogen', symbol: 'N2', percentage: 78.5, greenhouseEffect: 0.0 },
        { name: 'Oxygen', symbol: 'O2', percentage: 19.8, greenhouseEffect: 0.0 },
        { name: 'Argon', symbol: 'Ar', percentage: 1.1, greenhouseEffect: 0.0 },
        { name: 'Carbon Dioxide', symbol: 'CO2', percentage: 0.08, greenhouseEffect: 0.3 },
      ],
      greenhouseFactorK: 24,
      skyColorHex: '#fdba74',
      sunsetGlowHex: '#7c3aed',
      cloudCoveragePercent: 12,
      hazeDensity: 0.38,
      breathableHuman: true,
      toxicityAlerts: ['Extreme dehydration risk (aridity index < 5)', 'Silicate dust inhalation hazards'],
    },
    seaLevelPercent: 12,
    albedo: 0.38,
    meanAnnualSurfaceTempC: 34.2,
    seasonalTempVarianceC: 32.0,
    meanAnnualPrecipitationMm: 120,
    plateCount: 6,
    plates: [
      { id: 1, name: 'Great Erg Basal Shield', isOceanic: false, centerLat: 10, centerLon: -20, velocityMmYr: 18, headingDeg: 45, color: '#f59e0b' },
      { id: 2, name: 'Polar Aquifer Depression', isOceanic: false, centerLat: 75, centerLon: 110, velocityMmYr: 12, headingDeg: 190, color: '#06b6d4' },
    ],
    deepTimeMa: 0,
    minerals: STANDARD_MINERALS,
    isHabitable: true,
    calendar: {
      yearName: 'Solar Erg Cycle',
      hoursPerDay: 25.4,
      daysPerYear: 282,
      months: [
        { name: 'Dune-1', days: 47 }, { name: 'Dune-2', days: 47 }, { name: 'Dune-3', days: 47 },
        { name: 'Dune-4', days: 47 }, { name: 'Dune-5', days: 47 }, { name: 'Dune-6', days: 47 },
      ],
      weekdays: ['D1', 'D2', 'D3', 'D4', 'D5', 'D6'],
      currentYear: 142,
      currentMonth: 4,
      currentDay: 22,
      currentHour: 18,
    },
    eras: [
      { id: 'era-d1', name: 'Subsurface Sietch Founding', startYear: 1, endYear: 150, description: 'Moisture farming network establishes deep underground habitats.' },
    ],
    chronicle: [
      { id: 'ev-d1', year: 28, planetDay: 88, eraId: 'era-d1', title: 'Great Haboob of Khorasan', category: 'ecological', description: 'Massive dust wall spans 3,000 kilometers.' },
    ],
    lastModified: Date.now(),
  },

  ice_world: {
    id: 'planet-ice-boreas',
    name: 'Boreas Cryo-Prime',
    seed: 10293,
    archetype: 'ice_world',
    description: 'A glaciated snowball planet shrouded in kilometers-thick ice sheets over a warm subglacial ocean driven by geothermal vents.',
    radiusEarth: 0.98,
    massEarth: 0.88,
    densityGcm3: 5.12,
    surfaceGravityG: 0.92,
    escapeVelocityKms: 10.6,
    magneticFieldGauss: 0.44,
    semiMajorAxisAU: 1.85,
    eccentricity: 0.052,
    orbitalInclinationDeg: 1.5,
    argumentOfPeriapsisDeg: 140,
    orbitalPeriodDays: 890.2,
    axialTiltDeg: 16.5,
    rotationPeriodHours: 32.4,
    star: {
      name: 'Boreas Star',
      spectralType: 'G',
      massSolar: 0.98,
      luminositySolar: 0.92,
      radiusSolar: 0.97,
      effectiveTemperatureK: 5650,
      starColorHex: '#fff7ed',
      habitableZoneInnerAU: 0.91,
      habitableZoneOuterAU: 1.61,
    },
    moons: [],
    atmosphere: {
      surfacePressureAtm: 0.65,
      scaleHeightKm: 7.2,
      gases: [
        { name: 'Nitrogen', symbol: 'N2', percentage: 88.0, greenhouseEffect: 0.0 },
        { name: 'Oxygen', symbol: 'O2', percentage: 11.2, greenhouseEffect: 0.0 },
        { name: 'Argon', symbol: 'Ar', percentage: 0.7, greenhouseEffect: 0.0 },
        { name: 'Methane', symbol: 'CH4', percentage: 0.08, greenhouseEffect: 0.8 },
      ],
      greenhouseFactorK: 18,
      skyColorHex: '#93c5fd',
      sunsetGlowHex: '#f472b6',
      cloudCoveragePercent: 42,
      hazeDensity: 0.22,
      breathableHuman: false,
      toxicityAlerts: ['Hypoxia (low partial pressure of O2)', 'Severe hypothermia hazards (-55°C average)'],
    },
    seaLevelPercent: 55, // 55% ocean, but all frozen
    albedo: 0.68,
    meanAnnualSurfaceTempC: -58.4,
    seasonalTempVarianceC: 22.0,
    meanAnnualPrecipitationMm: 110,
    plateCount: 5,
    plates: [
      { id: 1, name: 'Glacial Shield 1', isOceanic: false, centerLat: 20, centerLon: -30, velocityMmYr: 15, headingDeg: 60, color: '#38bdf8' },
    ],
    deepTimeMa: 0,
    minerals: STANDARD_MINERALS,
    isHabitable: false,
    calendar: {
      yearName: 'Cryo-Cycle',
      hoursPerDay: 32.4,
      daysPerYear: 660,
      months: [{ name: 'Glacies-1', days: 110 }, { name: 'Glacies-2', days: 110 }, { name: 'Glacies-3', days: 110 }, { name: 'Glacies-4', days: 110 }, { name: 'Glacies-5', days: 110 }, { name: 'Glacies-6', days: 110 }],
      weekdays: ['Day-1', 'Day-2', 'Day-3', 'Day-4', 'Day-5'],
      currentYear: 50,
      currentMonth: 2,
      currentDay: 40,
      currentHour: 12,
    },
    eras: [],
    chronicle: [],
    lastModified: Date.now(),
  },

  venusian: {
    id: 'planet-venus-cytherea',
    name: 'Cytherea (Runaway Greenhouse)',
    seed: 6660,
    archetype: 'venusian',
    description: 'A hellish inferno locked in a runaway greenhouse effect. Crushing 94 atmospheres of carbon dioxide, sulfuric acid clouds, and molten lead temperatures.',
    radiusEarth: 0.95,
    massEarth: 0.82,
    densityGcm3: 5.24,
    surfaceGravityG: 0.91,
    escapeVelocityKms: 10.36,
    magneticFieldGauss: 0.01,
    semiMajorAxisAU: 0.72,
    eccentricity: 0.007,
    orbitalInclinationDeg: 3.4,
    argumentOfPeriapsisDeg: 55,
    orbitalPeriodDays: 224.7,
    axialTiltDeg: 177.3, // Retrograde
    rotationPeriodHours: 5832, // Super-slow retrograde
    star: {
      name: 'Helios Prime',
      spectralType: 'G',
      massSolar: 1.0,
      luminositySolar: 1.0,
      radiusSolar: 1.0,
      effectiveTemperatureK: 5778,
      starColorHex: '#fff7ed',
      habitableZoneInnerAU: 0.95,
      habitableZoneOuterAU: 1.68,
    },
    moons: [],
    atmosphere: {
      surfacePressureAtm: 94.2,
      scaleHeightKm: 15.9,
      gases: [
        { name: 'Carbon Dioxide', symbol: 'CO2', percentage: 96.5, greenhouseEffect: 1.0 },
        { name: 'Nitrogen', symbol: 'N2', percentage: 3.5, greenhouseEffect: 0.0 },
        { name: 'Sulfur Dioxide', symbol: 'SO2', percentage: 0.015, greenhouseEffect: 0.9 },
      ],
      greenhouseFactorK: 460,
      skyColorHex: '#eab308', // Opaque sulfury yellow
      sunsetGlowHex: '#ca8a04',
      cloudCoveragePercent: 100,
      hazeDensity: 0.95,
      breathableHuman: false,
      toxicityAlerts: ['Lethal surface temperature (464°C)', 'Crushing 94 atm pressure', 'Concentrated sulfuric acid precipitation'],
    },
    seaLevelPercent: 0,
    albedo: 0.76,
    meanAnnualSurfaceTempC: 464.0,
    seasonalTempVarianceC: 2.0,
    meanAnnualPrecipitationMm: 0,
    plateCount: 2,
    plates: [
      { id: 1, name: 'Basaltic Crustal Stagnant Lid', isOceanic: false, centerLat: 0, centerLon: 0, velocityMmYr: 0.5, headingDeg: 0, color: '#ca8a04' },
    ],
    deepTimeMa: 0,
    minerals: STANDARD_MINERALS,
    isHabitable: false,
    calendar: {
      yearName: 'Cytherean Revolution',
      hoursPerDay: 5832,
      daysPerYear: 0.92,
      months: [{ name: 'Sol', days: 1 }],
      weekdays: ['Day-1'],
      currentYear: 1,
      currentMonth: 1,
      currentDay: 1,
      currentHour: 100,
    },
    eras: [],
    chronicle: [],
    lastModified: Date.now(),
  },

  barren_mercurian: {
    id: 'planet-mercury-hermes',
    name: 'Hermes IV (Barren Basalt)',
    seed: 4321,
    archetype: 'barren_mercurian',
    description: 'An airless, heavily cratered iron-core world baking next to its star. Extreme day-to-night thermal swings from 430°C in sunlight to -180°C in deep shade.',
    radiusEarth: 0.38,
    massEarth: 0.055,
    densityGcm3: 5.43,
    surfaceGravityG: 0.38,
    escapeVelocityKms: 4.25,
    magneticFieldGauss: 0.003,
    semiMajorAxisAU: 0.387,
    eccentricity: 0.205,
    orbitalInclinationDeg: 7.0,
    argumentOfPeriapsisDeg: 29,
    orbitalPeriodDays: 87.97,
    axialTiltDeg: 0.03,
    rotationPeriodHours: 1407.6, // 3:2 spin-orbit resonance
    star: {
      name: 'Helios Prime',
      spectralType: 'G',
      massSolar: 1.0,
      luminositySolar: 1.0,
      radiusSolar: 1.0,
      effectiveTemperatureK: 5778,
      starColorHex: '#fff7ed',
      habitableZoneInnerAU: 0.95,
      habitableZoneOuterAU: 1.68,
    },
    moons: [],
    atmosphere: {
      surfacePressureAtm: 0.0000000000001, // Trace exosphere
      scaleHeightKm: 35.0,
      gases: [
        { name: 'Oxygen', symbol: 'O', percentage: 42.0, greenhouseEffect: 0.0 },
        { name: 'Sodium', symbol: 'Na', percentage: 29.0, greenhouseEffect: 0.0 },
        { name: 'Hydrogen', symbol: 'H', percentage: 22.0, greenhouseEffect: 0.0 },
      ],
      greenhouseFactorK: 0,
      skyColorHex: '#000000', // Pitch black vacuum
      sunsetGlowHex: '#000000',
      cloudCoveragePercent: 0,
      hazeDensity: 0.0,
      breathableHuman: false,
      toxicityAlerts: ['Hard vacuum', 'Lethal solar particle radiation', 'Micro-meteorite bombardment'],
    },
    seaLevelPercent: 0,
    albedo: 0.12,
    meanAnnualSurfaceTempC: 167.0,
    seasonalTempVarianceC: 280.0, // Wild day-night swing
    meanAnnualPrecipitationMm: 0,
    plateCount: 1,
    plates: [
      { id: 1, name: 'Single Rigid Iron Core Shell', isOceanic: false, centerLat: 0, centerLon: 0, velocityMmYr: 0, headingDeg: 0, color: '#64748b' },
    ],
    deepTimeMa: 0,
    minerals: STANDARD_MINERALS,
    isHabitable: false,
    calendar: {
      yearName: 'Hermetic Year',
      hoursPerDay: 1407.6,
      daysPerYear: 1.5,
      months: [{ name: 'Cycle-1', days: 1 }],
      weekdays: ['Day-1'],
      currentYear: 1,
      currentMonth: 1,
      currentDay: 1,
      currentHour: 50,
    },
    eras: [],
    chronicle: [],
    lastModified: Date.now(),
  },

  volcanic_io: {
    id: 'planet-volcanic-tartarus',
    name: 'Tartarus Caldera',
    seed: 9942,
    archetype: 'volcanic_io',
    description: 'A violently active volcanic world wracked by intense gravitational tidal flexure from a nearby gas giant parent. Continuous silicate and sulfur eruptions paint the surface in vivid yellows, blacks, and reds.',
    radiusEarth: 0.32,
    massEarth: 0.018,
    densityGcm3: 3.53,
    surfaceGravityG: 0.18,
    escapeVelocityKms: 2.56,
    magneticFieldGauss: 0.01,
    semiMajorAxisAU: 1.05,
    eccentricity: 0.004,
    orbitalInclinationDeg: 0.05,
    argumentOfPeriapsisDeg: 80,
    orbitalPeriodDays: 1.77,
    axialTiltDeg: 0.0,
    rotationPeriodHours: 42.5,
    star: {
      name: 'Helios Prime',
      spectralType: 'G',
      massSolar: 1.0,
      luminositySolar: 1.0,
      radiusSolar: 1.0,
      effectiveTemperatureK: 5778,
      starColorHex: '#fff7ed',
      habitableZoneInnerAU: 0.95,
      habitableZoneOuterAU: 1.68,
    },
    moons: [],
    atmosphere: {
      surfacePressureAtm: 0.000000001,
      scaleHeightKm: 25.0,
      gases: [
        { name: 'Sulfur Dioxide', symbol: 'SO2', percentage: 90.0, greenhouseEffect: 0.5 },
        { name: 'Sulfur Monoxide', symbol: 'SO', percentage: 5.0, greenhouseEffect: 0.0 },
      ],
      greenhouseFactorK: 2,
      skyColorHex: '#18181b',
      sunsetGlowHex: '#ea580c',
      cloudCoveragePercent: 4,
      hazeDensity: 0.25,
      breathableHuman: false,
      toxicityAlerts: ['Extreme tidal volcanism', 'Sulfur gas asphyxiation', 'Pyroclastic ejecta fields'],
    },
    seaLevelPercent: 0,
    albedo: 0.63,
    meanAnnualSurfaceTempC: -140.0,
    seasonalTempVarianceC: 25.0,
    meanAnnualPrecipitationMm: 0,
    plateCount: 8,
    plates: [
      { id: 1, name: 'Pele Magma Plume Basin', isOceanic: false, centerLat: -20, centerLon: -100, velocityMmYr: 120, headingDeg: 45, color: '#eab308' },
    ],
    deepTimeMa: 0,
    minerals: STANDARD_MINERALS,
    isHabitable: false,
    calendar: {
      yearName: 'Tidal Cycle',
      hoursPerDay: 42.5,
      daysPerYear: 200,
      months: [{ name: 'Magma-1', days: 50 }],
      weekdays: ['Day-1'],
      currentYear: 1,
      currentMonth: 1,
      currentDay: 1,
      currentHour: 10,
    },
    eras: [],
    chronicle: [],
    lastModified: Date.now(),
  },

  sub_neptune: {
    id: 'planet-gas-dwarf-aeolus',
    name: 'Aeolus Supercritical',
    seed: 3311,
    archetype: 'sub_neptune',
    description: 'A mini-Neptune gas dwarf with 2.4 Earth radii and 8.2 Earth masses. Enveloped in a deep hydrogen-helium atmosphere transitioning into a supercritical water-ammonia mantle.',
    radiusEarth: 2.45,
    massEarth: 8.2,
    densityGcm3: 3.12,
    surfaceGravityG: 1.36,
    escapeVelocityKms: 20.5,
    magneticFieldGauss: 2.4,
    semiMajorAxisAU: 1.35,
    eccentricity: 0.024,
    orbitalInclinationDeg: 2.2,
    argumentOfPeriapsisDeg: 190,
    orbitalPeriodDays: 574.0,
    axialTiltDeg: 28.0,
    rotationPeriodHours: 16.5,
    star: {
      name: 'Helios Prime',
      spectralType: 'G',
      massSolar: 1.0,
      luminositySolar: 1.0,
      radiusSolar: 1.0,
      effectiveTemperatureK: 5778,
      starColorHex: '#fff7ed',
      habitableZoneInnerAU: 0.95,
      habitableZoneOuterAU: 1.68,
    },
    moons: [
      {
        id: 'moon-aeolus-1',
        name: 'Zephyr',
        radiusEarth: 0.35,
        massEarth: 0.025,
        semiMajorAxisKm: 480000,
        eccentricity: 0.01,
        inclinationDeg: 1.2,
        orbitalPeriodDays: 12.5,
        isTidallyLocked: true,
        albedo: 0.35,
        colorHex: '#93c5fd',
        hasAtmosphere: true,
      },
    ],
    atmosphere: {
      surfacePressureAtm: 125.0, // Thick gas envelope
      scaleHeightKm: 32.0,
      gases: [
        { name: 'Hydrogen', symbol: 'H2', percentage: 78.0, greenhouseEffect: 0.2 },
        { name: 'Helium', symbol: 'He', percentage: 19.5, greenhouseEffect: 0.0 },
        { name: 'Methane', symbol: 'CH4', percentage: 2.1, greenhouseEffect: 0.8 },
      ],
      greenhouseFactorK: 120,
      skyColorHex: '#0284c7', // Cyan-azure gas mantle
      sunsetGlowHex: '#3b82f6',
      cloudCoveragePercent: 95,
      hazeDensity: 0.7,
      breathableHuman: false,
      toxicityAlerts: ['Crushing supercritical pressure', 'No solid rocky surface', 'Explosive hydrogen mixture'],
    },
    seaLevelPercent: 100, // Supercritical ocean
    albedo: 0.44,
    meanAnnualSurfaceTempC: 110.0,
    seasonalTempVarianceC: 12.0,
    meanAnnualPrecipitationMm: 5000,
    plateCount: 0,
    plates: [],
    deepTimeMa: 0,
    minerals: STANDARD_MINERALS,
    isHabitable: false,
    calendar: {
      yearName: 'Aeolian Year',
      hoursPerDay: 16.5,
      daysPerYear: 835,
      months: [{ name: 'A-1', days: 100 }],
      weekdays: ['D1', 'D2', 'D3'],
      currentYear: 1,
      currentMonth: 1,
      currentDay: 1,
      currentHour: 5,
    },
    eras: [],
    chronicle: [],
    lastModified: Date.now(),
  },
};

export const PLANET_PRESETS: PlanetData[] = Object.values(PRESET_PLANETS);

